name: Deploy to GitHub Pages

# mainブランチへのpushを検知
on:
  push:
    branches: [ "main" ]

  # Actions タブから手動で実行できるようにする
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ['18.x']
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      # パッケージのインストールとアプリのビルド
      - name: install and build
        run: |
          yarn install --frozen-lockfile
          yarn run build
        env:
          CI: true
      
      # GitHub Pages にデプロイ
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
          cname: speech.frogapp.net
